services:
  mysql-spring:
    container_name: mysql-spring
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  employee-service:
    build: .
    container_name: employee-service
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysql-spring
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysql-spring

