services:
  mysql-spring:
    container_name: mysql-spring
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  registry-service:
    build: registry-service
    container_name: registry-service
    ports:
      - 8036:8036
  api-gateway:
    build: api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql-spring
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      EUREKA_HOST: registry-service

    depends_on:
      - mysql-spring
      - registry-service

  employee-service:
    build: employee-service
    container_name: employee-service
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysql-spring
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      EUREKA_HOST: registry-service
    depends_on:
      - mysql-spring
      - registry-service

  department-service:
    build: department-service
    container_name: department-service
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysql-spring
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      EUREKA_HOST: registry-service
    depends_on:
      - mysql-spring
      - registry-service