# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: config-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 8088
      targetPort: 8088
  type: LoadBalancer
