# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
        - name: registry-service
          image: microservices/registry-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry-service
  ports:
    - port: 8761
      targetPort: 8761
  type: LoadBalancer
