server:
  port: 8080



eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8036/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.netflix.discovery: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/department/**

